import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://zgxemnyqllfdjuqupbmb.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpneGVtbnlxbGxmZGp1cXVwYm1iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3NDc1NDIyNSwiZXhwIjoxOTkwMzMwMjI1fQ.6qz0SU29jEad2QTwkSFUPz9jee1HUcdLT6tlVWTNYN8')